# Project name
name = "meteor-portfolio"

# ✅ Specify the output directory for Cloudflare Pages
pages_build_output_dir = "dist"

# ✅ Set compatibility date for Cloudflare
compatibility_date = "2024-02-08"
